#!/usr/bin/php
<?php
$rundir = dirname(readlink($argv[0]));
require_once ($rundir . '/rds_config.php');

if (isset($argv['1']) && $argv['1'] == 'autoconf') {
	echo 'yes' . "\n";
} else if (isset($argv['1']) && $argv['1']== 'config') {
	
	echo <<<EOM
graph_title $nodename Swap Usage
graph_args --base 1000 -l 0
graph_vlabel Swap Usage
graph_category AWS_RDS
graph_info The amount of swap space used on the DB Instance.
aws_rds_swap.label usage
aws_rds_swap.draw LINE2
aws_rds_swap.info The current Swap Usage.

EOM;
	
} else {

	$result = $client->getMetricStatistics(array(
		'Namespace'  => 'AWS/RDS',
		'MetricName' => 'SwapUsage',
		'Dimensions' => $dimensions,
		'StartTime'  => strtotime('-5 min'),
		'EndTime'    => strtotime('now'),
		'Period'     => 300,
		'Statistics' => array('Maximum'),
	));
	foreach ($result['Datapoints'] as $val) {
		echo 'aws_rds_swap.value ' . $val['Maximum'] . "\n";
	}

}
