#!/usr/bin/php
<?php
$rundir = dirname(readlink($argv[0]));
require_once ($rundir . '/rds_config.php');

if (isset($argv['1']) && $argv['1'] == 'autoconf') {
	echo 'yes' . "\n";
} else if (isset($argv['1']) && $argv['1']== 'config') {
	
	echo <<<EOM
graph_title $nodename Free Storage Space
graph_args --base 1000 -l 0
graph_vlabel Free Storage Space
graph_category AWS_RDS
graph_info The amount of available storage space.
aws_rds_space.label available
aws_rds_space.draw LINE2
aws_rds_space.info The current Free Storage Space.

EOM;
	
} else {

	$result = $client->getMetricStatistics(array(
		'Namespace'  => 'AWS/RDS',
		'MetricName' => 'FreeStorageSpace',
		'Dimensions' => $dimensions,
		'StartTime'  => strtotime('-5 min'),
		'EndTime'    => strtotime('now'),
		'Period'     => 300,
		'Statistics' => array('Maximum'),
	));
	foreach ($result['Datapoints'] as $val) {
		echo 'aws_rds_space.value ' . $val['Maximum'] . "\n";
	}

}
